#!/bin/bash

# Welcome message for Photon devcontainer
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║        🌟 Welcome to Photon Development Environment 🌟      ║"
echo "║                                                              ║"
echo "║  Photon - Incredibly fast crawler designed for OSINT        ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Installed Tools:"
echo "  ✓ Python $(python --version | cut -d' ' -f2)"
echo "  ✓ Git $(git --version | cut -d' ' -f3)"
echo "  ✓ GitHub CLI $(gh --version | head -n1 | cut -d' ' -f3)"
echo "  ✓ Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
echo "  ✓ Node.js $(node --version)"
echo ""
echo "🔧 Quick Commands:"
echo "  photon --help           - Show Photon help"
echo "  pytest                  - Run tests"
echo "  black .                 - Format code"
echo "  flake8 .                - Lint code"
echo "  bandit -r .             - Security scan"
echo ""
echo "📚 Documentation:"
echo "  https://github.com/s0md3v/Photon/wiki"
echo ""
echo "Happy Crawling! 🕷️"
echo ""
